FROM openjdk:11 as builder
WORKDIR /app
COPY gradle/ gradle/
COPY src/main/ src/main/
COPY build.gradle.kts gradle.properties gradlew settings.gradle.kts ./
RUN ./gradlew shadowJar

FROM azul/zulu-openjdk-alpine:11-jre
RUN apk --no-cache add curl
COPY --from=builder /app/build/libs/crystal-skull-all.jar crystal-skull-all.jar
COPY --from=builder /app/build/resources/main/ src/main/resources/
EXPOSE 8080
HEALTHCHECK --timeout=5s --start-period=5s --retries=1 \
    CMD curl -f http://localhost:8080/search?query=appl || exit 1
CMD ["java", "-server", "-jar", "crystal-skull-all.jar"]