version: '3.7'
services:
  test:
    image: gradle:6.0.1-jdk8
    command: bash wait-for-it.sh -t 0 quiz:80 -- gradle --no-daemon test
    volumes:
      - type: bind
        source: .
        target: /home/gradle
      - type: volume
        source: gradle-cache-test
        target: /home/gradle/.gradle
      - type: bind
        source: ./build/reports/tests
        target: /project/build/reports/tests
    depends_on: [quiz]
    networks: [backend]
    environment:
      SPACY_SERVER_URL: http://nlp:8080
      CRYSTAL_SKULL_URL: http://quiz:80
volumes:

  # There is a quiz service in docker-compose.override.yml. It uses the same Gradle dependencies as the test service.
  # Since both services need to write to the Gradle cache directory, separate volumes must be used to prevent file lock
  # exceptions.
  gradle-cache-test: