version: '3.7'
services:
  quiz:
    image: gradle:6.0.1-jdk8
    command: sh -c 'gradle --no-daemon -t installDist & gradle --no-daemon run'

    # The directory must be named "crystal-skull" because automatic reload watches a directory by that name.
    # The directory must be nested (i.e., "/crystal-skull" will not work).
    working_dir: /home/gradle/crystal-skull

    volumes:
      - type: bind
        source: .
        target: /home/gradle/crystal-skull
        consistency: cached # Prevents Docker for Mac bind mounts from being unusably slow.
      - type: volume
        source: gradle-cache
        target: /home/gradle/.gradle
volumes:
  gradle-cache: