version: '3.7'
services:
  quiz:
    build:
      dockerfile: docker/Dockerfile
      context: .
    # JDK 8 doesn't know how to manage its memory when it's in a container. JDK 9 fixed this, but Kotlin only supports
    # JDK 8. Hence, we have to use the relevant compiler options.
    command: java
      -server
      -XX:+UnlockExperimentalVMOptions
      -XX:+UseCGroupMemoryLimitForHeap
      -XX:InitialRAMFraction=2
      -XX:MinRAMFraction=2
      -XX:MaxRAMFraction=2
      -XX:+UseG1GC
      -XX:MaxGCPauseMillis=100
      -XX:+UseStringDeduplication
      -jar
      crystal-skull-all.jar