version: '3.7'
services:
  quiz:
    image: gradle:6.6.1-jdk14
    command: sh -c 'gradle --no-daemon -t installDist & gradle --no-daemon run'
    # The directory must be named "crystal-skull" because automatic reload watches a directory by that name.
    # The directory must be nested (i.e., "/crystal-skull" will not work).
    working_dir: /home/gradle/crystal-skull
    volumes:
      - type: bind
        source: .
        target: /home/gradle/crystal-skull
        consistency: cached # Prevents Docker for Mac bind mounts from being unusably slow.
      - type: volume
        source: gradle-cache-quiz
        target: /home/gradle/.gradle
  test:
    image: gradle:6.6.1-jdk14
    entrypoint: bash docker/wait-for-it.sh -t 0 quiz:80 --
    command: bash
    volumes:
      - type: bind
        source: .
        target: /home/gradle
      - type: volume
        source: gradle-cache-test
        target: /home/gradle/.gradle
    depends_on: [quiz]
    networks: [backend]
    environment:
      CRYSTAL_SKULL_URL: http://quiz:80
      SPACY_SERVER_URL: http://nlp:8000
volumes:
  # The quiz and test services use the same Gradle dependencies. Since both services need to write to the Gradle cache
  # directory, separate volumes must be used in order to prevent file lock exceptions.
  gradle-cache-quiz:
  gradle-cache-test: